chore: add office hour blog post 28-07
catenax-ng/catenax-ng.github.io pull request #198
Opened 2023-07-31 09:45 UTC by tomaszbarwicki

Fixes https://github.com/eclipse-tractusx/sig-infra/issues/203
Updates https://github.com/eclipse-tractusx/sig-infra/issues/93

2023-07-31 11:31 UTC, FaGru3n requested changes
litte typo

2023-07-31 11:31 UTC, FaGru3n commented on blog/2023-07-28-OfficeHours.md
> +- Question arised about reviewing open IP issue for Digital Twin Registry application. Advised that Eclipse Foundation needs to review that, as it's not DevOps scope. With regards to PR review, it wa
Question `arised`  --> Question `raised`

2023-07-31 11:32 UTC, FaGru3n approved these changes
LGTM

2023-07-31 14:04 UTC, tomaszbarwicki commented on blog/2023-07-28-OfficeHours.md
> +- Question arised about reviewing open IP issue for Digital Twin Registry application. Advised that Eclipse Foundation needs to review that, as it's not DevOps scope. With regards to PR review, it wa
Fixed.

2023-08-01 06:36 UTC, FaGru3n approved these changes
LGTM
<img src="https://media3.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>

2023-08-01 07:23 UTC, merged