docs: add office hour meeting minutes 2023-08-25
catenax-ng/catenax-ng.github.io pull request #200
Opened 2023-08-28 09:50 UTC by carslen

add recent office hour.

2023-08-28 10:15 UTC, hzierer requested changes
on small change request, rest LGTM.

2023-08-28 10:15 UTC, hzierer commented on blog/2023-08-25-OfficeHours.md
> +During accompanying the QG Checks a couple of things poped up:
I'm afraid "accompanying" is used by default only in a musical context. Maybe assistance or support?

2023-08-28 11:10 UTC, carslen commented on blog/2023-08-25-OfficeHours.md
> +During accompanying the QG Checks a couple of things poped up:
According to Langenscheidt it should be ok, but anyway I'm goint to change it for you :)

2023-08-28 12:37 UTC, Siegfriedk commented on blog/2023-08-25-OfficeHours.md
> +- Do not invent new legal documentation (e.g. ``COPYRIGHT.md`), please
is this an oversight/bug with 2 before COPYRIGHT.md and only one closing it?

2023-08-28 13:42 UTC, carslen commented on blog/2023-08-25-OfficeHours.md
> +- Do not invent new legal documentation (e.g. ``COPYRIGHT.md`), please
Fixed

2023-08-28 13:43 UTC, carslen commented on blog/2023-08-25-OfficeHours.md
> +- Upgradability of Postgresql Helm Charts
added context.

2023-08-30 16:26 UTC, hzierer submitted a review, later dismissed
LGTM

2023-08-30 16:26 UTC, hzierer commented on blog/2023-08-25-OfficeHours.md
> +During the QG Checks a couple of things poped up:
Better beginning, but totally missed already the first time that it should be "popped" and not "poped" - sorry.

2023-08-31 06:16 UTC, merged