chore: add office hour blog file for 061023
catenax-ng/catenax-ng.github.io pull request #211
Opened 2023-10-10 07:17 UTC by almadigabor

2023-10-12 11:57 UTC, FaGru3n requested changes
little typo

2023-10-12 11:57 UTC, FaGru3n commented on blog/2023-10-06-OfficeHours.md
> +- A [Release Planning board](https://github.com/orgs/eclipse-tractusx/projects/26/views/9)is available now on GitHub.
just a little blank
`A [Release Planning board](https://github.com/orgs/eclipse-tractusx/projects/26/views/9) is`

2023-10-13 11:08 UTC, almadigabor commented on blog/2023-10-06-OfficeHours.md
> +- A [Release Planning board](https://github.com/orgs/eclipse-tractusx/projects/26/views/9)is available now on GitHub.
thanks for the find, fixed it.

2023-10-13 11:15 UTC, FaGru3n approved these changes
LGTM

2023-10-16 07:36 UTC, merged