chore: add meetings minutes for office hour on 17-11-2023
catenax-ng/catenax-ng.github.io pull request #219
Opened 2023-11-22 10:53 UTC by FaGru3n

### Description of this Pull Request
#### What would be changed or will be added with this PR?
- add office hour 17-11-2023

fixes https://github.com/eclipse-tractusx/sig-infra/issues/374

#### Preview
![image](https://github.com/catenax-ng/catenax-ng.github.io/assets/121097161/b6c1bd91-c99d-452c-ace5-ad77aae3f1b9)

#### Testing 

- checkout branch
- npm install (optional)
- npm start
- verify changes

2023-11-22 12:18 UTC, SebastianBezold requested changes

2023-11-22 12:18 UTC, SebastianBezold commented on blog/2023-11-17-OfficeHours.md
> +- _Info_: Kyverno Policies will be getting in place planning to our clusters, and we're playing around with that
"in place planning to our clusters"?? 
suggestion:

`We are going to deploy [Kyverno](https://kyverno.io/) to our clusters. Goal: Verify Release Guidelines at deploy time; Warnings at first; might be enforced in future`

2023-11-22 12:18 UTC, SebastianBezold commented on blog/2023-11-17-OfficeHours.md
> +- HashiCorp Vault tokens for EDC deployments --> Be careful with your root vault token in your application! Please use the Argo CD Vault plugin mechanism.
Teams are not using the root token. This was just an example of the only token that does not expire. So just background info.

2023-11-22 12:18 UTC, SebastianBezold commented on blog/2023-11-17-OfficeHours.md
> +- Token discussions will be supported by Security Team contact them under [sig-security repo](https://github.com/eclipse-tractusx/sig-security/issues/new/choose)
by Security Team. Contact -> new sentence starting here

2023-11-22 12:18 UTC, SebastianBezold commented on blog/2023-11-17-OfficeHours.md
> +- YouTube Videos from [Eclipse Foundation Con](https://www.youtube.com/@EclipseFdn) are available
It's EclipseCon not Eclipse Foundation Con

2023-11-22 12:18 UTC, SebastianBezold commented on blog/2023-11-17-OfficeHours.md
> +- Congrats to [Andrea Bertagnolli](https://github.com/ndr-brt) was successfully voted to be a committer in the [Eclipse Tractus-X project](https://projects.eclipse.org/projects/automotive.tractusx)
on a successful election. or end sentence after name and start the new one with "He was successfully elected"

2023-11-22 13:28 UTC, FaGru3n commented on blog/2023-11-17-OfficeHours.md
> +- _Info_: Kyverno Policies will be getting in place planning to our clusters, and we're playing around with that
always good to have a second pair of eyes

2023-11-22 13:45 UTC, FaGru3n commented on blog/2023-11-17-OfficeHours.md
> +- Congrats to [Andrea Bertagnolli](https://github.com/ndr-brt) was successfully voted to be a committer in the [Eclipse Tractus-X project](https://projects.eclipse.org/projects/automotive.tractusx)
[d62868a](https://github.com/catenax-ng/catenax-ng.github.io/pull/219/commits/d62868af87380365e2008292d9159bc3fa2a15b7)

2023-11-22 13:45 UTC, FaGru3n commented on blog/2023-11-17-OfficeHours.md
> +- YouTube Videos from [Eclipse Foundation Con](https://www.youtube.com/@EclipseFdn) are available
[d62868a](https://github.com/catenax-ng/catenax-ng.github.io/pull/219/commits/d62868af87380365e2008292d9159bc3fa2a15b7)

2023-11-22 13:45 UTC, FaGru3n commented on blog/2023-11-17-OfficeHours.md
> +- Token discussions will be supported by Security Team contact them under [sig-security repo](https://github.com/eclipse-tractusx/sig-security/issues/new/choose)
[d62868a](https://github.com/catenax-ng/catenax-ng.github.io/pull/219/commits/d62868af87380365e2008292d9159bc3fa2a15b7)

2023-11-22 13:45 UTC, FaGru3n commented on blog/2023-11-17-OfficeHours.md
> +- Token discussions will be supported by Security Team contact them under [sig-security repo](https://github.com/eclipse-tractusx/sig-security/issues/new/choose)
https://github.com/catenax-ng/catenax-ng.github.io/pull/219/commits/95c24e5f1bff1c749ff9e740365ba50c419c51e3

2023-11-22 13:47 UTC, FaGru3n commented
Thx to you @SebastianBezold

2023-11-28 13:18 UTC, tomaszbarwicki approved these changes
LGTM :)

2023-11-28 13:20 UTC, merged