doc/a1odt-831 refactor documentation setup aks cluster via tf
catenax-ng/catenax-ng.github.io pull request #99
Opened 2022-09-15 09:39 UTC by kastade

2022-09-15 11:29 UTC, jofromm approved these changes

2022-09-15 14:47 UTC, SebastianBezold requested changes

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-onboard-teams-to-any-environment.md
> +## Vault Via Terraform
I guess 'via' should be written lowercase

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +SP `DevSecOpsAutomation` (stored in Hashicorp Vault path: `devsecops/azure/demo.catena-x.net/service-principals/automation`).
No need for the specific SP name here. If internal names are not necessary for following the instructions, please do not add them

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +    container_name       = "vault-tfstate"
We should provide specific instruction on which properties to change. In this case
container_name and key, to avoid overwriting existing states

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +Change the environment variables as desired in the `terraform.tfvars`
'environment variables' could lead to confusion. Suggestion: configuration properties

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +### Set up child cluster
Suggestion: remote cluster instead of child cluster, since it would be operable, even if the core Argo CD instance is not available anymore

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +copy an existing values.yaml, rename and insert actual loadbalancer-IP (public IP in Azure)
What should be the name of the copied file?

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +copy an existing 'values-tls.yaml', rename and change `cluster-name` and `certificate/dnsZone`
What should be the name of the copied file?

2022-09-15 14:47 UTC, SebastianBezold commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +#### Adding remote clusters to an ApplicationSet
Will this section filled in a follow-up PR?

2022-10-20 12:47 UTC, kastade commented on docs/internal/how-to-onboard-teams-to-any-environment.md
> +## Vault Via Terraform
done

2022-10-20 12:53 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +SP `DevSecOpsAutomation` (stored in Hashicorp Vault path: `devsecops/azure/demo.catena-x.net/service-principals/automation`).
name of SP deleted; path remains so that the account can be found in Vault

2022-10-20 13:05 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +    container_name       = "vault-tfstate"
added container_name

2022-10-20 13:10 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +Change the environment variables as desired in the `terraform.tfvars`
changed

2022-10-20 13:12 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +### Set up child cluster
changed

2022-10-20 13:22 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +copy an existing values.yaml, rename and insert actual loadbalancer-IP (public IP in Azure)
done

2022-10-20 13:23 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +copy an existing 'values-tls.yaml', rename and change `cluster-name` and `certificate/dnsZone`
done

2022-10-21 09:59 UTC, kastade commented on docs/internal/how-to-setup-aks-cluster-via-terraform.md
> +#### Adding remote clusters to an ApplicationSet
it was copied and in my opinion not necessary

2022-11-04 11:50 UTC, kastade commented
Did not meet the team's expectations

2022-11-04 11:50 UTC, closed without merging